apiVersion: apps/v1
kind: Deployment
metadata:
  name:  clase3
  labels:
    app:  clase3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clase3
  template:
    metadata:
      labels:
        app:  clase3
    spec:
      containers:
      - name: hola-aws101
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 80