apiVersion: apps/v1
kind: Deployment
metadata:
  name:  clase3
  labels:
    app:  clase3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clase3
  template:
    metadata:
      labels:
        app:  clase3
    spec:
      containers:
        - name: clase3
          image: "$REPOSITORY_URI":"$TAG"
          ports:
          - containerPort: 80
